service: my-service

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  timeout: 10

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false
    migration:
      dir: offline/migrations

resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: my-table

functions:
  createItem:
    handler: src/handlers/item-create.handler
    events:
      - http:
          path: /items
          method: post
  getItem:
    handler: src/handlers/item-get.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/handlers/item-update.handler
    events:
      - http:
          path: /items/{id}
          method: put
  deleteItem:
    handler: src/handlers/item-delete.handler
    events:
      - http:
          path: /items/{id}
          method: delete
  listItems:
    handler: src/handlers/item-list.handler
    events:
      - http:
          path: /items
          method: get
  queryItems:
    handler: src/handlers/item-query.handler
    events:
      - http:
          path: /items/query
          method: post
  listTableItems:
    handler: src/handlers/table-list.handler
    events:
      - http:
          path: /table/{tableName}
          method: get
